version: '3.8'

services:
  twitter-auth:
    container_name: ${IMG_NAME:-lotso-twitter-auth}
    image: lotso-twitter-auth:latest
    volumes:
      - ${HOST_CERT_FOLDER}:${CONTAINER_CERT_FOLDER}
    build: .
    environment:
      DOCKER_ENV: "true"
      PRIVKEY_PATH: ${PRIVKEY_PATH}
      CERT_PATH: ${CERT_PATH}
      SERVER_PORT: ${SERVER_PORT:-5000}
      MONGODB_DB: ${MONGODB_DB:-twitterLogs}
      MONGODB_USERDB: ${MONGODB_USERDB:-twitterUsers}
      MONGODB_PORT: 27017
      MONGODB_USERNAME: ${MONGODB_USERNAME:-admin}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
      MONGODB_HOST: mongodb
      REDIS_HOST: redis
      REDIS_PORT: 6379
      AIRDROP_SERVER_HOST: airdrop-server
      AIRDROP_SERVER_PORT: 1423
      AIRDROP_PER_STEP: ${AIRDROP_PER_STEP:-25000}
      AIRDROP_REWARD_MAX_FOR_BUYER: ${AIRDROP_REWARD_MAX_FOR_BUYER:-10000000}
      AIRDROP_REWARD_MAX_FOR_NOT_BUYER: ${AIRDROP_REWARD_MAX_FOR_NOT_BUYER:-2000000}
      AIRDROP_PER_PERSON: ${AIRDROP_PER_PERSON:-50000}
      LOTSO_PURCHASED_USER_AMOUNT: ${LOTSO_PURCHASED_USER_AMOUNT:-100000}
      WEBPAGE_ADDRESS: ${WEBPAGE_ADDRESS:-https://lotso.org}
      AUTH_WEB_ADDRESS: ${AUTH_WEB_ADDRESS:-https://api.btiplatform.com}
      CHECK_RETWEET_ENABLED: ${CHECK_RETWEET_ENABLED:-false}
      CHECK_TWEET_ENABLED: ${CHECK_TWEET_ENABLED:-false}
      CHECK_LIKE_ENABLED: ${CHECK_LIKE_ENABLED:-true}
    ports:
      - "${SERVER_PORT:-5000}:${SERVER_PORT:-5000}"
    depends_on:
      - mongodb
      - redis
      # - airdrop-server
    restart: always
    networks:
      - ${DOCKER_NETWORK:-lotso-main-network}

  mongodb:
    container_name: ${MONGODB_IMG_NAME:-mongodb}
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    volumes:
      - "${MONGODB_PATH:-/root/mongodb}:/data/db"
    restart: always
    networks:
      - ${DOCKER_NETWORK:-lotso-main-network}

  redis:
    container_name: ${REDIS_IMG_NAME:-redis}
    image: redis:latest
    ports:
      - "${REDIS_PORT:-6000}:6379"
    restart: always
    networks:
      - ${DOCKER_NETWORK:-lotso-main-network}

networks:
  lotso-main-network:
    external: true
  lotso-dev-network:
    external: true